# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasker.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import logick

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 908)
        MainWindow.setStyleSheet("QFrame{\n"
"    background-color: rgb(53, 53, 79)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(414, 240, 701, 641))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setTabletTracking(False)
        self.label.setText("")
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.label.setWordWrap(True)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 240, 421, 641))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        font.setPointSize(15)
        font.setUnderline(True)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("border : 2px solid black;\n"
"background : darkblue;")
        self.listWidget.setObjectName("listWidget")
        self.listWidget.itemClicked.connect(self.update_task)
        self.listWidget.itemClicked.connect(self.delete_task)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 50, 231, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border:2px solid #14c8dc;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 12pt Times New Roman;")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 50, 791, 111))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border:2px solid #14c8dc;\n"
"border-radius:8px;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 12pt Times New Roman;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 141, 31))
        self.label_2.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 10, 151, 31))
        self.label_3.setWordWrap(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.add_task())
        self.pushButton.setGeometry(QtCore.QRect(10, 180, 331, 51))
        self.pushButton.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.add_item())
        self.pushButton_2.setGeometry(QtCore.QRect(380, 180, 321, 51))
        self.pushButton_2.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget,  clicked = lambda : self.delete_task_sql())
        self.pushButton_3.setGeometry(QtCore.QRect(730, 180, 361, 51))
        self.pushButton_3.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"background-color:#000000ff;\n"
"color: rgb(20, 200, 220);\n"
"border-radius:5px;\n"
"border:1px solid white")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(-10, 160, 1121, 81))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1111, 161))
        self.label_5.setObjectName("label_5")
        self.label_5.raise_()
        self.listWidget.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setCheckable(False)
        self.action.setChecked(False)
        self.action.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.action.setObjectName("action")

        self.retranslateUi(MainWindow)
        self.add_item()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Планировщик"))
        self.label_2.setText(_translate("MainWindow", "Название"))
        self.label_3.setText(_translate("MainWindow", "Описание"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Обновить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.action.setText(_translate("MainWindow", "Создать"))

    def add_item(self):
        self.listWidget.clear()
        item = logick.view_task()
        for item_list in item:
            print(item_list)
            self.listWidget.addItem(item_list[0])

    def add_task(self): 
        name = self.lineEdit.text() 
        text = self.lineEdit_2.text()
        logick.create_task(name,text)
        self.lineEdit.setText("Добавлено!!!")
        
    def delete_task(self,item):
        a = self.lineEdit.setText(item.text())
        
    def delete_task_sql(self):
        b = self.lineEdit.text()
        logick.delete_task(b)

    def update_task(self,item):
        list_item = logick.get_task_text(item.text())
        self.label.setText(list_item[1])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
